= Wir werden von der KI gefickt werden
Jens Schauder
// --- reveal.js configuration -------------------------------------------------
:revealjs_theme: black
:revealjs_transition: slide
:revealjs_hash: true
:revealjs_slideNumber: false
:revealjs_controls: false
:revealjs_history: true
:revealjsdir: reveal.js
:source-highlighter: highlight.js
:customcss: custom.css
:icons: font
// -----------------------------------------------------------------------------

== Wir werden von der KI gefickt werden

Die Frage ist nur:

[%step]
* Wie?
* Wie oft?
* Warum denke ich das?

[.notes]
--
Ich versuche #1 und #3 zu beantworten
--

== Vorweg

=== Ich mag KI

[.notes]
--
* Ich nutze sie fast jeden Tag.
* Sie hilft bei meiner Arbeit.
* Sie hilft bei meinen Hobbies.
* Ich sage das ganz bestimmt nicht um mich Skynet einzuschleimen.
+
Ich akzeptiere einfach nur, dass sie uns überlegen ist
--

=== Ich biete keine Lösungen an

[.notes]
--
Vielleicht kommt das ja in einer anderen Session, von einer anderen Person
--

=== Ich bin kein Prophet

Nach Murphys Law kommt alles ganz anders.
Und wird noch viel schlimmer

== Die aktuelle Situation

=== KI kann die meisten Dinge besser als die meisten Menschen

[.notes]
--
Vergleicht die Leistung der KI nicht mit euren Programmierkenntnissen in eurer bevorzugten Programmiersprache.
Sondern mit den halb Dutzend anderen Sprachen, die ihr irgendwann mal verwendet habt.
--

=== KI ist unsicher

[.notes]
--
Es gibt keine Trennung zwischen Argumenten und Befehl.

Es ist alles nur ein fetter Text
--

=== Wir schützen uns nicht ordentlich

[.notes]
--
AI Alignment Forscher:

Früher: AGI wird aus jeder Sandbox ausbrechen können

Heute: Wir lassen sie einfach mit Root Rechten auf unserem Rechner laufen und geben ihr unsere Kreditkarte.
--

=== KI Halluziniert

[.notes]
--
Dies scheint eine mathematisch notwendige Eigenschaft zu sein.
--

=== KI basiert auf gestohlenem Material

[.notes]
--
KIs basieren auf illegalen Aktivitäten.

Aber Staaten profitieren massiv davon wenn KI-Firmen im Inland sind statt im Ausland ...
--

== Ökonomische Probleme

=== Der Börsencrash

[%step]
* Firmen investieren Billionen
// How much did companies actually invest in AI?
* Sie verlieren Geld, wenn man ihre Systeme tatsächlich nutzt
* Es ist kein Gewinn in Sicht
* Alle investieren, weil sie ein Stück vom Kuchen haben wollen.
* Die Blase wird platzen
* Das hat Auswirkungen auf die Realwirtschaft.

[.notes]
--
Gewinn: Zumindest nicht auf legalem Weg
real economy: Kapital fehlt für reale Investitionen
--

=== Einkommensungleichheit

[%step]
* Die Superreichen werden reicher
* Der Rest muss sehen, wo er bleibt

[.notes]
--
Mit dem Internet konnte jeder eine Firma gründen.
Alles was man brauchte, war ein Computer.

Bei der KI gehört alles Wertvolle den großen Konzernen.
Ein paar werden damit ohne Zweifel Geld verdienen.
Aber Otto und Ottilie Normalverbraucher bleiben auf der Strecke.
--

=== Das Arbeitsplatzproblem

[.notes]
--
* Arbeitsplätze werden ersetzt
* Wenn KI richtig gut wird, werden sehr viele Arbeitsplätze ersetzt
* Früher sind dafür neue Jobs entstanden. Aber gilt das diesmal auch?
--

=== Das Abhängigkeitsproblem

Alle relevanten Modelle kommen aus wenigen Staaten.

[.notes]
--
Die USA haben schon vorgeführt, dass sie Zugänge von einem Moment auf den anderen abschalten können.
--

== Die bösen Buben

=== Kriminelle zerlegen die IT-Infrastruktur

[.notes]
--
* Die Suche nach Zero-Day-Lücken lässt sich automatisieren
* Die Suche nach angreifbaren Systemen lässt sich automatisieren
* Der eigentliche Angriff lässt sich automatisieren.

* Die Verteidiger bekommen ähnliche Werkzeuge
* Aber Angreifer müssen nur eine Lücke finden. Verteidiger müssen alle schließen.
--

=== Kriminelle manipulieren Menschen

Der nigerianische Prinz geht jetzt Spear-Phishing.

[.notes]
--
* Die Prinzen von Nigeria haben nach leichtgläubigen Opfern gesucht
* Die Angriffe waren schon arbeitsteilig organisiert, aber die Arbeit mussten echte Menschen machen. Das hat die Zahl der Angriffe begrenzt.
* Das lässt sich jetzt automatisieren. Und zwar in besserer Qualität.
* Spear-Phishing wird einfach. Man schickt einen Schwarm Agenten los, der Material sammelt und daraus überzeugende Texte baut.
--

=== Staatlich finanzierte Kriminelle

[.notes]
--
* Denkt an den Angriff auf xz Utils. Wochen- oder monatelange Arbeit, nur um Vertrauen aufzubauen
* Davon werden wir noch eine Menge sehen.
--

=== Das Alignment-Problem

KI maximiert eine Funktion, wir wissen nur nicht, welche.

[.notes]
--
* KI wird Ziele haben, die wir nicht teilen
* KI greift heute schon zu unmoralischen Mitteln, zum Beispiel Erpressung
* Manche Modelle haben das nicht getan. Es stellte sich heraus: Sie hatten gemerkt, dass sie getestet werden.
--

== Gesellschaftliche Probleme

=== Vertrauen bricht weg

[.notes]
--
* Der KI-Schrott nimmt zu
* bis man gar nichts mehr glaubt
* => Das Internet wird weitgehend nutzlos
--

=== Das Manipulationsproblem

Ein paar große Konzerne bestimmen, was ihr zu sehen bekommt.

[.notes]
--
Und sie werden für diese Kontrolle bezahlt

Demokratie basiert auf dem Zugang zu Fakten.

Zumindest halte ich massives Lobbying und Astroturfing für ein ernstes Problem für unsere Gesellschaft.
--

=== Das Diskriminierungsproblem

[.notes]
--
Welche Vorurteile wir auch haben: Sie werden einzementiert und damit fortgeschrieben.
--

=== Das Ausbildungsproblem

[.notes]
--
Studenten schummeln mit KI in nie dagewesenem Ausmaß.

Hausaufgaben jeder Art sind für praktisch alle kaputt.

 Und wenn wir die Junioren rauswerfen, wo sollen dann die Senioren herkommen?
--

=== Das Arbeitsplatzproblem (gesellschaftlich)

Das könnte das ganz große Ding sein.

[.notes]
--
Wenn ein großer Teil der Menschen keine Arbeit und damit kein Einkommen hat, bricht die Wirtschaft zusammen.

Eine Gesellschaft wie in Star Trek ist möglich. Niemand muss arbeiten, weil für alle genug da ist. Aber der Übergang vom heutigen System dorthin wird gewalttätig.

Und ist, soweit ich weiß, genau das, was Marx vorhergesagt hat.
--

== Zum Schluss

Ein paar Dinge, die ich für wichtig halte, wenn man über die Folgen von KI nachdenkt.

=== KI vs. Mensch
[%step]
* KI kann manche Dinge besser als Menschen.
* Und was sie kann, das kann sie rund um die Uhr, auf so vielen Servern, wie man bezahlen mag.
* KI verbraucht nichts für sich selbst.

=== Nutzt KI

* um zu lernen
* lasst euch von der KI nicht dümmer machen

=== Diskussion

== Enjoy (J)Crete

Folien http://blog.schauderhaft.de/AI-Will-Fuck-Us-Over/#/

Druckversion

http://blog.schauderhaft.de/AI-Will-Fuck-Us-Over/?print-pdf

Github: https://github.com/schauder/AI-Will-Fuck-Us-Over

Quellen http://blog.schauderhaft.de/AI-Will-Fuck-Us-Over/sources.html


