= AI will fuck us over
Jens Schauder
// --- reveal.js configuration -------------------------------------------------
:revealjs_theme: black
:revealjs_transition: slide
:revealjs_hash: true
:revealjs_slideNumber: c/t
:revealjs_history: true
:revealjsdir: reveal.js
:source-highlighter: highlight.js
:customcss: custom.css
:icons: font
// -----------------------------------------------------------------------------

== AI will fuck us over

The questions are:

[%step]
* How?
* How often?
* Why can we be so sure about this?

[.notes]
--
I'll try to answer question 1 and 3
--

== Preface

=== I love AI

[.notes]
--
* I use it almost every day.
* It helps with my work.
* It helps with my hobbies.
* I'm not claiming this to appease our AI overlords.

	I'm just accepting  there superiority
--

=== I won't offer solutions

[.notes]
--
Maybe that come in a different session from some other person
--

=== I'm not a prophet

[.notes]
--
According to Murphy's law it will turn ugly in a totally different, very surprising and very bad way.
--

== The current situation

=== AI is better at most things than most humans

[.notes]
--
Don't compare it with your level of programming in your favorite language. Look at their knowledge compared to your knowledge in e.g. politics, or biology.
--

=== AI is inherently insecure

[.notes]
--
No distinction between commands and arguments.
Just one big chunk of text.

There is no way to securely prevent Jail breaking
--

=== We are not protecting ourselves properly

[.notes]
--
No distinction between commands and arguments.
Just one big chunk of text.

There is no way to securely prevent Jail breaking
--

=== Models hallucinate

[.notes]
--
There seems strong indication that this is just an inherent property of the technology
--

=== AI is stolen material

[.notes]
--
The whole AI is brought to use by illegal activity.

But states profit massively from having AI companies in their jurisdiction, so ...
--

== Economic Problems

=== The Stock Crash

[%step]
* Companies invest billions
// How much did companies actually invest in AI?
* They lose money on actual usage
* No profit in sight
* Everybody invests to get part of the cake
* Eventually the bubble will crash
* This will affect the real economy

[.notes]
--
Profit: At least not in a legal way
real economy: Don't know why.
--

=== The Income Disparity Problem

[%step]
* The super rich will become richer.
* The rest not so much

[.notes]
--
With the internet you could start a business.
All you needed was a computer.

With AI, all the valuable stuff is owned by big companies.
Without doubt a few will make money out of it.
But the average Jane and Joe will be left in the dust.
--

=== The Job problem

[.notes]
--
* Jobs get replaced
* If AI gets really good, a lot of jobs get replaced
* In the past new jobs where created. But will that be the case this time?
--

== The Bad Actors

=== Criminals Breaking IT-Infrastructure

[.notes]
--
* Search for zero-day vulnerabilities can be automated
* Search for attackable systems can be automated
* The actual attack can be automated.

* Defenders get similar boosts
* But attackers just have to find one weak spot. Defenders have to close all of them
--

=== Criminals manipulating people

The Nigerian prince goes spear-fishing.

[.notes]
--
* Princes of Nigeria where looking for gullible victims
* Attacks used specialization of work, but still real people had to do the work, limiting the attacks that could be performed.
* This can now be automated. With better quality.
* Spear fishing becomes easier. Just send a swarm of agents out to collect material and to produce convincing material.
--

=== State sponsored criminals

[.notes]
--
* Consider the attack on xz Utils. Elaborate work for weeks or months to gain trust
* We are going to see a lot of this.
--

=== The Alignment Problem

AI ist maximizing a function, we just don't know which one.

[.notes]
--
* AI will have goals we don't share
* AI already does use immoral things like blackmailing people
* Some models didn't do that. Turns out they were realizing that they are getting tested.
--

== Social Problems

=== Disruption of trust

[.notes]
--
* AI slop increases
* until you don't believe anything anymore
* => The Internet becomes mostly useless
--

=== The Manipulation Problem

A few big companies will control what you get to see.

[.notes]
--
And they will get paid for that control

Democracy is based on access to factual information.

At least I consider intense lobbying and astroturfing a serious problem for our society.
--

=== The discrimination problem

[.notes]
--
Whatever biases we have will get codified and thereby perpetuated.
--

=== The Training Problem

[.notes]
--
Students use AI cheating in an unprecedented way.

Any kind of homework is basically broken for almost everybody.

 If we fire the juniors, where will the seniors come from?
--

=== The Job Problem (Social)

This might be the big one.

[.notes]
--
If a large percentage of people is out of jobs and therefore out of income, the economy will collapse.

A society as sketched out by Star Trek is possible. No one has to work, because there is plenty to go around. But the transition of the current system to this system is going to be violent.

And is AFAIK exactly what Marx predicted.
--

== Final Notes

A couple of things I consider relevant when thinking about the effects of AI.

=== AI vs Human
[%step]
* AI can do some things better than Humans.
* Those it can, it can do 24/7 on as many servers as you want to pay for.
* AI does not consume anyting for it's own good.

=== Use AI

* to learn
* don't let I make you dumber

=== Discuss

== Enjoy (J)Crete